### PR TITLE
added new Activity Type: system commands

### PR DESCRIPTION
**Pull request by skobkars**
New Activity Type: System Commands

Sends commands line by line to your Pi (or other host) and stops processing in case of an error.

Outputs of all commands are logged in octoprint.log

### CODE REVIEW

**Comment by LuxuSam** [comment]
Nice thank you very much! On first glance it looks well coded and also fits my coding stile. I will look at it more thoroughly tomorrow :)

**Comment by LuxuSam** [comment]
The PR looks good, just one question. Why did you add GPIO 2 & 3? As far as I can see, those have preconfigured pull-up resistors. Won't that be a problem when applying that again on my button setup function or won't that make a difference?

**Comment by skobkars** [comment]
Hi Sam,

Applying pull-ups on ## 2,3 is harmless and it works just fine. I have
added them (especially #3) for a very simple reason actually: as #3 is used
to wake-up/start RPi after shutting down, connecting a single button to it
allows it to be used for both shutting down and starting up processes for
example.

In fact, in my case I only have one button to start with, so it is used for
toggling LED lights when the printer is up, for turning printer on (Octopi
is running) if it was down, and for starting up the whole setup (Printer +
Octopi) if the Octopi was down. Very convenient.

Regards,

Sergey

**Comment by LuxuSam** [comment]
Cool thanks for clearing that up :)

I'll probably release your changes in the weekend :)

**Comment by skobkars** [comment]
Awesome!

Glad you find it useful.

**Pull request merged**
